_core:
  default_config_hash: 3ooO-bLkru7Jl91Kb8hO7pD1divveu98PTIZQiCV3pQ
langcode: en
site_settings:
  default_icon: home-smoke
  theme_color: coat-of-arms
  koro: basic
footer_settings:
  footer_color: dark
  footer_top_title: 'Contact us'
  footer_top_content:
    value: "<ul class=\"menu\"><li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Helsinki-info advisory service\" data-protocol=\"false\" href=\"https://www.hel.fi/kanslia/neuvonta-en/\">Helsinki-info advisory service</a></li><li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Contact information search\" data-protocol=\"false\" href=\"https://numerot.hel.fi/\">Contact information search</a></li><li class=\"menu__item menu__item--external\"><a class=\"link\" data-design=\"link\" data-link-text=\"Give feedback\" data-protocol=\"false\" href=\"https://www.hel.fi/feedback/\">Give feedback</a></li></ul>\r\n"
    format: full_html
